### ISSUE TITLE
generate from scripts is not working , and @code path is showing error in test , in config file the path for code is day2 i dont know why

### ISSUE THREAD

**Issue by chidam333** [ThePrimeagen/kata-machine#10]
**It's a win 11 machine**
**running day cmd works though it generates new day**

<br>

![clear - kata-machine - Visual Studio Code 9_16_2022 11_03_46 PM](https://user-images.githubusercontent.com/86545749/190699068-ef63381a-19eb-456b-8af4-02eb9744bbd5.png)

**Comment by chidam333** [comment]
Wait lol as i was opening this issue i tried to change the day in tsconfig and test are now tests are passing . Still the generate script is not getting executed . I think it might be a real bug .

**Comment by classyrazy** [comment]
I also have this same error I think it's a bug

**Comment by patllamas** [comment]
I'm also having the same issue. I upgrade to the latest recommended version of Node (v16.17.0) and I'm running the latest Yarn (1.22.19). I just can't seem to get yarn generate to work either without the "generate is not recognized as an internal or external command"

**Comment by ThePrimeagen** [comment]
ohh
i see

its.... pathing!!!! oh no!  Yeah, this is exclusively a windows issue, if anyone wanna make a PR, please, i'll accept.

i don't have a windows box :)

**Comment by ThePrimeagen** [comment]
this should have been fixed with #11
