### ISSUE TITLE
Lig-Machine hasn't currently documented the complex initialism that defines it's name

### ISSUE THREAD

**Issue by npmaile** [ThePrimeagen/kata-machine#3]
obviously it would be stupid to name a project some random name without it being an initialism. 
this issue is just to document what that initialism is

**Comment by npmaile** [comment]
is it 
Literal 
Interpretation of
Great 
- (to)
Mediocre
Algorithms
Containing
Horrendous
Interpreted
codE

**Comment by ThePrimeagen** [comment]
I feel like we shouldn't simply limit ourselves to just ligma.  There are a rainbow of ways to sugma nuts and I don't want you getting stuck with mind goblins running around while you imagine dragons.  I even heard that ye died from ligma

**Comment by npmaile** [comment]
```
long-winded
instrumentation
generating
massive
anticompetitive
computational
help for
intermediate
coders
