### ISSUE TITLE
tail not getting set to undefined when queue.length === 1 in dequeue() function

### ISSUE THREAD

**Issue by AdityaAgrawal-03** [ThePrimeagen/kata-machine#35]
In the code block -

```
deque(): T | undefined {
        if (!this.head) {
            return undefined;
        }

        this.length--;

        const head = this.head;
        this.head = this.head.next;

        head.next = undefined;

        return head.value;
    }
```

If the queue length is 1 and we dequeue the element, the tail will still point to the last element as we're not setting it to anything in the above deque function.
 
Now, if we enqueue another element:

- the head will be `undefined` as `this.tail` already exists and enqueue() will not set the head to any value.Attaching enqueue function code for reference: 

```
enqueue(item: T): void {
        this.length++;

        const node = { value: item } as Node<T>;
       
       // below condition will be false after dequeueing the last element
        if (!this.tail) {
            this.tail = this.head = node;

            return;
        }

        this.tail.next = node;
        this.tail = node;
    }
```
- Now if you peek head, it will give `undefined` instead of last inserted element. The test written in `src/__tests__/Queue.ts` was also failing because of this issue.

**Proposed solution:**

Add this condition in dequeue function:
```
if (this.length === 1) {
            this.tail = this.head?.next
        }
```

**Comment by canicjusz** [comment]
he fixed it during the Q&A section

**Comment by itse4elhaam** [comment]
faced the same issue and fixed it that way.
