### ISSUE TITLE
Yarn generate fails

### ISSUE THREAD

**Issue by MoeRayo** [ThePrimeagen/kata-machine#7]
Hello, I keep running into this error every time I run `yarn generate`

```js
yarn run v1.22.19
$ ./scripts/generate
'.\scripts\generate' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```
The error above is preventing the **days** folders from been generated.

Is this specific to my machine? I'd be glad if I could get a pointer on how to fix this.
Thank you

**Comment by felipe-miranda-marreiros** [comment]
Go to terminal:

cd scripts
node generate
yarn -s day

**Comment by MoeRayo** [comment]
Thank you Felipe.
That works!
